export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const SORT_COUNTRIES = "SORT_COUNTRIES";
export const COUNTRY_DETAILS = "COUNTRY_DETAILS";
export const ALL_ACTIVITIES = "ALL_ACTIVITIES";
export const ACTIVITIES_OF_COUNTRY = "ACTIVITIES_OF_COUNTRY";